package janet.ui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;

/**
 * Displays one chat message and a compact speaker badge.
 */
public class DialogBox extends HBox {
    /**
     * Creates a dialog box with alignment and styles for one speaker.
     *
     * @param message message to display
     * @param speaker short label identifying the speaker
     * @param isUser whether the speaker is the user
     */
    private DialogBox(String message, String speaker, boolean isUser) {
        Label messageLabel = new Label(message);
        messageLabel.setWrapText(true);
        messageLabel.setMaxWidth(430.0);
        messageLabel.getStyleClass().addAll("message-bubble", isUser ? "user-bubble" : "janet-bubble");

        Label speakerBadge = new Label(speaker);
        speakerBadge.getStyleClass().addAll("speaker-badge", isUser ? "user-badge" : "janet-badge");

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        setAlignment(Pos.TOP_CENTER);
        setMaxWidth(Double.MAX_VALUE);
        getStyleClass().add("dialog-row");

        if (isUser) {
            getChildren().addAll(spacer, messageLabel, speakerBadge);
        } else {
            getChildren().addAll(speakerBadge, messageLabel, spacer);
        }
    }

    /**
     * Creates a right-aligned dialog for a user command.
     *
     * @param message command entered by the user
     * @return user dialog box
     */
    public static DialogBox getUserDialog(String message) {
        return new DialogBox(message, "YOU", true);
    }

    /**
     * Creates a left-aligned dialog for Janet's response.
     *
     * @param message response generated by Janet
     * @return Janet dialog box
     */
    public static DialogBox getJanetDialog(String message) {
        return new DialogBox(message, "J", false);
    }
}
